### ISSUE TITLE
Storage module progression

### ISSUE THREAD

**Issue by Jkwolf25** [NFINIT-Development/AstroBlock#54]
Trying to complete the storage section in the quest book with the iron backpacks and it does not detect either the storage emphasis or upgrade emphasis backpacks on the iron tier. 

Similarly, in order to complete the minestrappolation 5 backpack, I cannot obtain fine leather because the tannic for tanning hides requires tanning solvent which cannot be crafted due to the recipe requiring a Minecraft  "Uncraftable Potion" which also does not have a crafting recipe (and appears to otherwise be unobtainable). Perhaps this is by design, but even if it is, the loot crates only offer possibly one tannic (just the regular one) and/or 6 fine leather which is still not enough to complete the 8 fine leather needed for the backpack. There is also the possibility that pack progression blocks the tanning recipe? 

Both issues have occurred since 1.27 (maybe prior I did not try to progress in storage until then)

**Comment by Heregerifa** [comment]
Quest book not recognising items is a recurrent problem.  You may have to cheat the item in, which will then be recognised, and (if you are honest) then deleting the extra item.  I had a similar problem with mekanism factories but - following an update - the opposite problem that completing 1 gave you the rewards for all!  Hopefully this is a compatibility issue that will be fixed in the future.

**Comment by Jkwolf25** [comment]
Ah! I see... well, I would like to legitimately obtain the tanning solvent. I did try the "cheat in" for the iron backpacks, (I have like 3-4 already, so I deleted them anyhow as I didnt need them) and it worked. I guess I will wait for the Minestrapolation backpack to allow for a craftable potion.
