### ISSUE TITLE
Quest Issues

### ISSUE THREAD

**Issue by jmdev91** [NFINIT-Development/AstroBlock#84]
I can't seem to get the Iron Backpacks progression to complete, specifically the iron tier. Neither version works, possibly because I crafted all the way to diamond tier in one go (without closing the crafting interface).
I was also sitting at 99% on the 100k FE quest, despite the Task Screen displaying 100k/100k. This just suddenly worked after stepping on my Chargepad, even though I'm sure I'd used it multiple times since first selecting that task (different play sessions, though).

**Comment by sojakai** [comment]
Did you make Both Iron Backpacks? It wants both to complete for some reason when it's not necessary to make the "Upgrade" Backpacks as the upgrades have not been added to the current versions of I.B. since they recoded it. The few upgrades that are in the mod or pretty much useless in this pack compared to just making the "Storage" Backpack.

**Comment by quillo-xi** [comment]
In my 2 worlds of AstroBlock (a solo and a co-op world) I have bad this issue for each of the Iron, Gold and Diamond backpacks.

It does not complete/update when you craft each of the variants. It was circumvented by entering Creative Mode and pulling one of the variants from thin air, then promptly deleting the item.
